import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { Copy, Trash2, Download, FileText, Keyboard, Moon, Sun } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { useToast } from "@/hooks/use-toast";
import { convert, ConversionMode } from "@/lib/converter";
import { Document, Packer, Paragraph, TextRun, Header, Footer, PageNumber, AlignmentType, BorderStyle } from "docx";
import { saveAs } from "file-saver";
import { useTheme } from "@/components/theme-provider";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";

export default function Home() {
  const [input, setInput] = useState("");
  const [mode, setMode] = useState<ConversionMode>("unicode");
  const [output, setOutput] = useState("");
  const { toast } = useToast();
  const { theme, setTheme } = useTheme();

  useEffect(() => {
    const savedMode = localStorage.getItem("spsinhalish-mode");
    if (savedMode === "unicode" || savedMode === "legacy") {
      setMode(savedMode);
    }
  }, []);

  useEffect(() => {
    setOutput(convert(input, mode));
  }, [input, mode]);

  const handleModeChange = (val: string) => {
    if (val === "unicode" || val === "legacy") {
      setMode(val as ConversionMode);
      localStorage.setItem("spsinhalish-mode", val);
    }
  };

  const copyToClipboard = () => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    toast({
      title: "Copied to clipboard",
      description: "Your Sinhala text has been copied.",
    });
  };

  const clearText = () => {
    setInput("");
    setOutput("");
    toast({
      title: "Text cleared",
    });
  };

  const downloadTxt = () => {
    if (!output) return;
    const blob = new Blob([output], { type: "text/plain;charset=utf-8" });
    saveAs(blob, `SPsinhalish-${new Date().getTime()}.txt`);
  };

  const downloadDocx = async () => {
    if (!output) return;

    const doc = new Document({
      sections: [
        {
          headers: {
            default: new Header({
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: "SPsinhalish",
                      bold: true,
                      size: 28,
                      color: "E65C00", // Saffron
                    }),
                  ],
                }),
              ],
            }),
          },
          footers: {
            default: new Footer({
              children: [
                new Paragraph({
                  alignment: AlignmentType.CENTER,
                  children: [
                    new TextRun("Generated by SPsinhalish - Page "),
                    new TextRun({
                      children: [PageNumber.CURRENT],
                    }),
                  ],
                }),
              ],
            }),
          },
          children: [
            new Paragraph({
              border: {
                top: { color: "auto", space: 1, value: BorderStyle.SINGLE, size: 6 },
                bottom: { color: "auto", space: 1, value: BorderStyle.SINGLE, size: 6 },
              },
              children: [
                new TextRun({
                  text: "Converted Text",
                  bold: true,
                  size: 24,
                }),
              ],
              spacing: { after: 400 },
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: output,
                  size: 24,
                  font: mode === "legacy" ? "FMAbhaya" : "Noto Sans Sinhala",
                }),
              ],
            }),
          ],
        },
      ],
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, `SPsinhalish-export-${new Date().getTime()}.docx`);
  };

  const wordCount = (text: string) => text.trim().split(/\s+/).filter(w => w.length > 0).length;

  return (
    <div className="min-h-[100dvh] flex flex-col items-center">
      <header className="w-full border-b bg-card/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="container max-w-6xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-bold tracking-tight text-primary">SPsinhalish</h1>
            <span className="hidden sm:inline-block text-sm text-muted-foreground ml-2">Singlish → Sinhala, instantly</span>
          </div>

          <div className="flex items-center gap-4">
            <ToggleGroup type="single" value={mode} onValueChange={handleModeChange} className="bg-muted p-1 rounded-lg">
              <ToggleGroupItem value="unicode" className="data-[state=on]:bg-background data-[state=on]:shadow-sm rounded-md px-3 py-1 text-sm font-medium transition-all">
                Unicode
              </ToggleGroupItem>
              <ToggleGroupItem value="legacy" className="data-[state=on]:bg-background data-[state=on]:shadow-sm rounded-md px-3 py-1 text-sm font-medium transition-all">
                Legacy (FM-Abhaya)
              </ToggleGroupItem>
            </ToggleGroup>
            
            <Button variant="ghost" size="icon" onClick={() => setTheme(theme === "dark" ? "light" : "dark")}>
              {theme === "dark" ? <Sun className="h-5 w-5" /> : <Moon className="h-5 w-5" />}
            </Button>
          </div>
        </div>
      </header>

      <main className="flex-1 w-full container max-w-6xl mx-auto px-4 py-8 flex flex-col gap-6">
        {mode === "legacy" && (
          <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="bg-primary/10 text-primary-foreground/80 text-sm px-4 py-3 rounded-lg border border-primary/20 text-center text-primary">
            <strong>Legacy Mode Active:</strong> Copy & paste into MS Word, then apply FM-Abhaya font.
          </motion.div>
        )}

        <div className="flex flex-wrap items-center justify-between gap-4">
          <div className="flex gap-2 flex-wrap">
            <Button variant="outline" size="sm" onClick={copyToClipboard} disabled={!output}>
              <Copy className="h-4 w-4 mr-2" />
              Copy
            </Button>
            <Button variant="outline" size="sm" onClick={clearText} disabled={!input}>
              <Trash2 className="h-4 w-4 mr-2" />
              Clear
            </Button>
            <Button variant="outline" size="sm" onClick={downloadTxt} disabled={!output}>
              <FileText className="h-4 w-4 mr-2" />
              .txt
            </Button>
            <Button variant="outline" size="sm" onClick={downloadDocx} disabled={!output}>
              <Download className="h-4 w-4 mr-2" />
              .docx
            </Button>
          </div>

          <Dialog>
            <DialogTrigger asChild>
              <Button variant="secondary" size="sm">
                <Keyboard className="h-4 w-4 mr-2" />
                Typing Guide
              </Button>
            </DialogTrigger>
            <DialogContent className="max-w-2xl max-h-[80vh]">
              <DialogHeader>
                <DialogTitle>Singlish Typing Guide</DialogTitle>
              </DialogHeader>
              <ScrollArea className="h-[60vh] pr-4">
                <div className="space-y-6 pb-4 text-sm">
                  <div>
                    <h3 className="font-semibold text-lg border-b pb-2 mb-3">Vowels</h3>
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                      <div className="flex justify-between p-2 bg-muted rounded"><span>a</span><span>අ</span></div>
                      <div className="flex justify-between p-2 bg-muted rounded"><span>aa</span><span>ආ</span></div>
                      <div className="flex justify-between p-2 bg-muted rounded"><span>ae</span><span>ඇ</span></div>
                      <div className="flex justify-between p-2 bg-muted rounded"><span>i</span><span>ඉ</span></div>
                      <div className="flex justify-between p-2 bg-muted rounded"><span>ii</span><span>ඊ</span></div>
                      <div className="flex justify-between p-2 bg-muted rounded"><span>u</span><span>උ</span></div>
                      <div className="flex justify-between p-2 bg-muted rounded"><span>uu</span><span>ඌ</span></div>
                      <div className="flex justify-between p-2 bg-muted rounded"><span>e</span><span>එ</span></div>
                    </div>
                  </div>
                  <div>
                    <h3 className="font-semibold text-lg border-b pb-2 mb-3">Consonants</h3>
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                      <div className="flex justify-between p-2 bg-muted rounded"><span>k</span><span>ක</span></div>
                      <div className="flex justify-between p-2 bg-muted rounded"><span>g</span><span>ග</span></div>
                      <div className="flex justify-between p-2 bg-muted rounded"><span>t</span><span>ට</span></div>
                      <div className="flex justify-between p-2 bg-muted rounded"><span>d</span><span>ඩ</span></div>
                      <div className="flex justify-between p-2 bg-muted rounded"><span>n</span><span>න</span></div>
                      <div className="flex justify-between p-2 bg-muted rounded"><span>p</span><span>ප</span></div>
                      <div className="flex justify-between p-2 bg-muted rounded"><span>b</span><span>බ</span></div>
                      <div className="flex justify-between p-2 bg-muted rounded"><span>m</span><span>ම</span></div>
                    </div>
                  </div>
                  <div>
                    <h3 className="font-semibold text-lg border-b pb-2 mb-3">Examples</h3>
                    <div className="grid sm:grid-cols-2 gap-2">
                      <div className="flex justify-between p-2 bg-muted rounded"><span>mama</span><span>මම</span></div>
                      <div className="flex justify-between p-2 bg-muted rounded"><span>gedara</span><span>ගෙදර</span></div>
                      <div className="flex justify-between p-2 bg-muted rounded"><span>kohomada</span><span>කොහොමද</span></div>
                      <div className="flex justify-between p-2 bg-muted rounded"><span>lassanai</span><span>ලස්සනයි</span></div>
                    </div>
                  </div>
                </div>
              </ScrollArea>
            </DialogContent>
          </Dialog>
        </div>

        <div className="grid md:grid-cols-2 gap-6 flex-1 min-h-[400px]">
          <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} className="flex flex-col h-full rounded-xl border bg-card shadow-sm overflow-hidden focus-within:ring-1 focus-within:ring-ring transition-shadow">
            <div className="px-4 py-2 border-b bg-muted/30 text-xs font-medium text-muted-foreground flex justify-between">
              <span>English (Singlish)</span>
              <span>{input.length} chars • {wordCount(input)} words</span>
            </div>
            <Textarea 
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="mama gedara yanawa..."
              className="flex-1 resize-none border-0 focus-visible:ring-0 rounded-none p-4 text-lg font-mono placeholder:text-muted-foreground/50 bg-transparent h-full min-h-[300px]"
            />
          </motion.div>

          <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} className="flex flex-col h-full rounded-xl border bg-card shadow-sm overflow-hidden">
            <div className="px-4 py-2 border-b bg-muted/30 text-xs font-medium text-muted-foreground flex justify-between">
              <span>Sinhala Output</span>
              <span>{output.length} chars • {wordCount(output)} words</span>
            </div>
            <div className="flex-1 p-4 overflow-auto bg-transparent relative">
              {!output ? (
                <div className="absolute inset-0 flex items-center justify-center text-muted-foreground/30 pointer-events-none p-6 text-center">
                  <p className="text-xl">Your translated text will appear here</p>
                </div>
              ) : (
                <div 
                  className={`text-xl leading-relaxed whitespace-pre-wrap ${mode === 'legacy' ? 'font-mono tracking-widest' : 'font-sinhala text-2xl'}`}
                  style={mode === 'legacy' ? { fontSize: '1.25rem' } : undefined}
                >
                  {output}
                </div>
              )}
            </div>
          </motion.div>
        </div>
      </main>

      <footer className="w-full py-6 mt-auto border-t bg-muted/20">
        <div className="container max-w-6xl mx-auto px-4 text-center text-sm text-muted-foreground">
          Crafted in Colombo
        </div>
      </footer>
    </div>
  );
}
