import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Header,
  Footer,
  PageNumber,
  AlignmentType,
  BorderStyle,
  HeadingLevel,
  ShadingType,
} from "docx";
import { saveAs } from "file-saver";
import type { ConvertMode } from "./converter";

const SAFFRON = "C2410C";
const DEEP_BROWN = "3D2F1F";
const SOFT_GRAY = "6B7280";

export async function exportDocx(content: string, mode: ConvertMode) {
  const fontName = mode === "legacy" ? "FM Abhaya" : "Iskoola Pota";
  const timestamp = new Date();
  const dateStr = timestamp.toLocaleDateString("en-GB", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const headerParagraph = new Paragraph({
    alignment: AlignmentType.LEFT,
    children: [
      new TextRun({
        text: "SPsinhalish",
        bold: true,
        size: 28,
        color: SAFFRON,
        font: "Calibri",
      }),
      new TextRun({
        text: "   Singlish to Sinhala Converter",
        size: 18,
        color: SOFT_GRAY,
        font: "Calibri",
      }),
    ],
  });

  const footerParagraph = new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [
      new TextRun({
        text: "Generated by SPsinhalish   |   Page ",
        size: 16,
        color: SOFT_GRAY,
        font: "Calibri",
      }),
      new TextRun({
        children: [PageNumber.CURRENT],
        size: 16,
        color: SOFT_GRAY,
        font: "Calibri",
      }),
      new TextRun({
        text: " of ",
        size: 16,
        color: SOFT_GRAY,
        font: "Calibri",
      }),
      new TextRun({
        children: [PageNumber.TOTAL_PAGES],
        size: 16,
        color: SOFT_GRAY,
        font: "Calibri",
      }),
    ],
  });

  const titleBlock: Paragraph[] = [
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 400, after: 0 },
      shading: {
        type: ShadingType.CLEAR,
        color: "auto",
        fill: "FAF6EE",
      },
      border: {
        top: { style: BorderStyle.SINGLE, size: 18, color: SAFFRON },
        bottom: { style: BorderStyle.SINGLE, size: 6, color: SAFFRON },
        left: { style: BorderStyle.SINGLE, size: 6, color: SAFFRON },
        right: { style: BorderStyle.SINGLE, size: 6, color: SAFFRON },
      },
      children: [
        new TextRun({
          text: "Sinhala Document",
          bold: true,
          size: 44,
          color: DEEP_BROWN,
          font: "Calibri",
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 0, after: 200 },
      shading: {
        type: ShadingType.CLEAR,
        color: "auto",
        fill: "FAF6EE",
      },
      border: {
        bottom: { style: BorderStyle.SINGLE, size: 6, color: SAFFRON },
        left: { style: BorderStyle.SINGLE, size: 6, color: SAFFRON },
        right: { style: BorderStyle.SINGLE, size: 6, color: SAFFRON },
      },
      children: [
        new TextRun({
          text: dateStr,
          italics: true,
          size: 20,
          color: SOFT_GRAY,
          font: "Calibri",
        }),
      ],
    }),
    new Paragraph({
      spacing: { before: 600, after: 0 },
      children: [new TextRun({ text: "" })],
    }),
  ];

  const lines = content.split(/\r?\n/);
  const bodyParagraphs: Paragraph[] = lines.map((line) =>
    new Paragraph({
      heading: HeadingLevel.HEADING_3 === undefined ? undefined : undefined,
      spacing: { line: 360, after: 120 },
      children: [
        new TextRun({
          text: line || " ",
          font: fontName,
          size: 28,
          color: DEEP_BROWN,
        }),
      ],
    }),
  );

  const doc = new Document({
    creator: "SPsinhalish",
    title: "SPsinhalish Export",
    description: "Generated by SPsinhalish",
    styles: {
      default: {
        document: {
          run: { font: "Calibri", size: 22 },
        },
      },
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 1000,
              right: 1000,
              bottom: 1000,
              left: 1000,
            },
          },
        },
        headers: {
          default: new Header({ children: [headerParagraph] }),
        },
        footers: {
          default: new Footer({ children: [footerParagraph] }),
        },
        children: [...titleBlock, ...bodyParagraphs],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  const ts = `${timestamp.getFullYear()}${String(timestamp.getMonth() + 1).padStart(2, "0")}${String(timestamp.getDate()).padStart(2, "0")}-${String(timestamp.getHours()).padStart(2, "0")}${String(timestamp.getMinutes()).padStart(2, "0")}`;
  saveAs(blob, `SPsinhalish-export-${ts}.docx`);
}
