kind = "web"
previewPath = "/"
title = "SPsinhalish"
version = "1.0.0"
id = "artifacts/spsinhalish"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24383

[services.development]
run = "pnpm --filter @workspace/spsinhalish run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/spsinhalish", "run", "build" ]
publicDir = "artifacts/spsinhalish/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24383"
BASE_PATH = "/"
